import { type Strength } from 'src/types/audit-insights';

export type InsightsLabels = {
  summaryHeading: string;
  summaryStrengths: string;
  summaryBlockers: string;
  summaryWeek: string;
  summaryMonth: string;
  summaryQuarter: string;
  summaryWrittenBy: (model: string) => string;
  summaryAllVerified: string;
  summarySomeUnverified: string;
  unverifiedMarker: (numbers: string) => string;
  strengthsHeading: string;
  strengthsEmpty: string;
  describeStrength: (strength: Strength, areaLabels: Record<string, string>) => string;
  aiReadinessItems: Record<'CRAWLERS' | 'LLMS_TXT' | 'ORGANIZATION' | 'FAQ', string>;
  comparisonHeading: string;
  comparisonSentence: (rulesOnly: number, withJudgement: number) => string;
  comparisonHint: string;
  pagesHeading: string;
  pagesIntro: string;
  confidenceSentence: (definitive: number, total: number, percent: number) => string;
  columnPage: string;
  columnType: string;
  columnIntent: string;
  columnHelpful: string;
  columnSpecific: string;
  columnTrust: string;
  columnSure: string;
  needsCheck: string;
  sure: string;
  morePages: (count: number) => string;
  weakestCardsHeading: string;
  pageTypes: Record<string, string>;
  intents: Record<string, string>;
  competingHeading: string;
  competingIntro: string;
  locationsHeading: string;
  locationsIntro: string;
  searchesPerMonth: string;
};
