import { type SeoArea } from 'src/types/seo-area';

type SectionLabels = { eyebrow: string; plain: string; accent: string };

export type ReportDesignLabels = {
  heroEyebrow: (domain: string, date: string) => string;
  heroHeadline: string;
  metaPages: string;
  metaDate: string;
  metaEngines: string;
  gaugeCaption: string;
  gradeWord: string;
  technicalOnlyScore: (technicalScore: number) => string;
  marquee: string[];
  openReport: string;
  sections: {
    summary: SectionLabels;
    scorecard: SectionLabels;
    strengths: SectionLabels;
    ai: SectionLabels;
    aiReadiness: SectionLabels;
    findings: SectionLabels;
    pages: SectionLabels;
    market: SectionLabels;
    opportunities: SectionLabels;
    roadmap: SectionLabels;
    method: SectionLabels;
  };
  strengthTitles: Record<'STRONG_AREAS' | 'TOP_RANKINGS' | 'HELPFUL_PAGES' | 'AI_READINESS' | 'AI_PRESENCE', string>;
  scorecardLead: string;
  tasksInArea: (count: number) => string;
  impactEyebrow: string;
  impactTitle: (technicalScore: number, score: number) => string;
  impactHint: string;
  whyItMatters: string;
  areaImpact: Record<SeoArea, string>;
  affected: string;
  affectedMore: (count: number) => string;
  findingsLead: (shown: number, total: number) => string;
  otherFindingsHeading: string;
  otherFindingsLead: (count: number, areaCount: number) => string;
  aiReadinessChips: string;
  aiPresence: string;
  aiTestedOn: (date: string) => string;
  pagesLead: string;
  roadmapLead: string;
  roadmapUnits: { WEEK: string; MONTH: string; QUARTER: string };
  roadmapDaysUnit: string;
  roadmapMeasures: (count: number) => string;
  roadmapNothing: string;
  roadmapResult: string;
  methodCards: { crawl: string; judged: string; summary: string; limits: string };
  methodCrawl: (pages: number, date: string) => string;
  methodJudged: string;
  methodSummary: string;
  methodLimits: string;
  ctaEyebrow: string;
  ctaLine1: string;
  ctaLine2: string;
  ctaText: string;
  ctaButton: string;
  headerButton: string;
  footerLegal: string;
  footerStudio: string;
};
