import { type SeoArea } from 'src/types/seo-area';
import { type SeoEffort } from 'src/types/seo-effort';
import { type SeoPriority } from 'src/types/seo-priority';
import { type SeoTaskSource } from 'src/types/seo-task-source';

export type ReportLabels = {
  title: string;
  generatedOn: string;
  score: string;
  grade: string;
  pagesChecked: string;
  areasHeading: string;
  areaColumn: string;
  scoreColumn: string;
  summaryHeading: string;
  strongestArea: string;
  weakestArea: string;
  taskCount: string;
  criticalCount: string;
  noTasks: string;
  tasksHeading: string;
  horizonWeek: string;
  horizonMonth: string;
  horizonQuarter: string;
  priorityColumn: string;
  effortColumn: string;
  sourceColumn: string;
  taskColumn: string;
  affectedUrls: string;
  moreUrls: string;
  reviewHeading: string;
  reviewIntro: string;
  methodologyHeading: string;
  methodology: string;
  contentNotAssessed: string;
  areas: Record<SeoArea, string>;
  priorities: Record<SeoPriority, string>;
  efforts: Record<SeoEffort, string>;
  sources: Record<SeoTaskSource, string>;
};
