import { type SeoArea } from 'src/types/seo-area';
import { type SeoEffort } from 'src/types/seo-effort';
import { type SeoPriority } from 'src/types/seo-priority';
import { type SeoTaskSource } from 'src/types/seo-task-source';

export type ReportLabels = {
  title: string;
  generatedOn: string;
  score: string;
  grade: string;
  pagesChecked: string;
  areasHeading: string;
  areaColumn: string;
  scoreColumn: string;
  summaryHeading: string;
  strongestArea: string;
  weakestArea: string;
  taskCount: string;
  criticalCount: string;
  noTasks: string;
  tasksHeading: string;
  horizonWeek: string;
  horizonMonth: string;
  horizonQuarter: string;
  priorityColumn: string;
  effortColumn: string;
  sourceColumn: string;
  taskColumn: string;
  affectedUrls: string;
  moreUrls: string;
  reviewHeading: string;
  reviewIntro: string;
  methodologyHeading: string;
  methodology: string;
  contentNotAssessed: string;
  marketDataNotConfigured: string;
  marketHeading: string;
  marketNotes: string;
  lighthouseHeading: string;
  performanceScore: string;
  largestContentfulPaint: string;
  layoutShift: string;
  blockingTime: string;
  aiReadinessHeading: string;
  aiReadinessIntro: string;
  aiReadinessCheckColumn: string;
  aiReadinessStatusColumn: string;
  crawlerAccess: string;
  crawlerAllowed: string;
  crawlerBlocked: string;
  present: string;
  missing: string;
  llmsTxt: string;
  organizationMarkup: string;
  faqMarkup: string;
  aiVisibilityHeading: string;
  aiVisibilityIntro: string;
  aiVisibilityPresence: string;
  aiVisibilityTestedOn: string;
  questionColumn: string;
  namedInsteadColumn: string;
  statusCited: string;
  statusMentioned: string;
  statusAbsent: string;
  statusUnknown: string;
  keywordsTotal: string;
  trafficEstimate: string;
  positionsHeading: string;
  opportunitiesHeading: string;
  keywordColumn: string;
  positionColumn: string;
  volumeColumn: string;
  pageColumn: string;
  notRelevantHeading: string;
  notRelevantIntro: string;
  backlinksHeading: string;
  backlinksTotal: string;
  referringDomains: string;
  brokenBacklinkPages: string;
  competitorsHeading: string;
  domainColumn: string;
  commonKeywordsColumn: string;
  trafficColumn: string;
  keywordCategories: Record<'QUICK_WIN' | 'NEAR_PAGE_ONE', string>;
  areas: Record<SeoArea, string>;
  priorities: Record<SeoPriority, string>;
  efforts: Record<SeoEffort, string>;
  sources: Record<SeoTaskSource, string>;
};
