type SectionLabels = { eyebrow: string; plain: string; accent: string };

export type ReportDesignLabels = {
  heroEyebrow: (domain: string, date: string) => string;
  heroHeadline: string;
  metaPages: string;
  metaDate: string;
  metaEngines: string;
  gaugeCaption: string;
  gradeWord: string;
  rulesOnlyAverage: (rulesOnly: number) => string;
  marquee: string[];
  openReport: string;
  sections: {
    summary: SectionLabels;
    scorecard: SectionLabels;
    ai: SectionLabels;
    findings: SectionLabels;
    pages: SectionLabels;
    market: SectionLabels;
    opportunities: SectionLabels;
    strengths: SectionLabels;
    roadmap: SectionLabels;
    method: SectionLabels;
  };
  strengthTitles: Record<'STRONG_AREAS' | 'TOP_RANKINGS' | 'HELPFUL_PAGES' | 'AI_READINESS' | 'AI_PRESENCE', string>;
  scorecardLead: string;
  tasksInArea: (count: number) => string;
  noTasksInArea: string;
  impactEyebrow: string;
  impactTitle: (rulesOnly: number, score: number) => string;
  impactHint: string;
  summaryBlockers: string;
  summaryStrengths: string;
  evidence: string;
  recommendation: string;
  affected: string;
  effortLabel: string;
  sourceLabel: string;
  horizonLabel: string;
  moreMeasures: string;
  findingsLead: (shown: number, total: number) => string;
  aiReadinessChips: string;
  aiPresence: string;
  aiTestedOn: (date: string) => string;
  pagesLead: string;
  noPages: string;
  roadmapUnits: { WEEK: string; MONTH: string; QUARTER: string };
  roadmapDaysUnit: string;
  roadmapResult: string;
  methodCards: { crawl: string; judged: string; summary: string; limits: string };
  methodCrawl: (pages: number, date: string) => string;
  methodJudged: string;
  methodSummary: (model: string, isFullyVerified: boolean) => string;
  methodNoSummary: string;
  ctaEyebrow: string;
  ctaLine1: string;
  ctaLine2: string;
  ctaText: (tasks: number) => string;
  ctaButton: string;
  headerButton: string;
  footerLegal: string;
  footerStudio: string;
};
