import { defineObject, FieldType } from 'twenty-sdk/define';

import {
  SEO_AUDIT_LANGUAGE,
  SEO_AUDIT_STATUS,
} from 'src/constants/seo-audit.constants';
import { buildSelectOptions } from 'src/utils/build-select-options';

export const SEO_AUDIT_UNIVERSAL_IDENTIFIER = 'b72492d4-f893-4d43-8c4c-bbccdfa9176d';

export const SEO_AUDIT_NAME_FIELD_UNIVERSAL_IDENTIFIER = 'e69f6c4d-46dd-4b10-aee4-15a66d7a305e';
export const SEO_AUDIT_DOMAIN_FIELD_UNIVERSAL_IDENTIFIER = '3dfb2d16-5d51-4024-a850-2104af6597e0';
export const SEO_AUDIT_STATUS_FIELD_UNIVERSAL_IDENTIFIER = 'ab3a894e-dfee-47dd-a9ca-1e5183505693';
export const SEO_AUDIT_LANGUAGE_FIELD_UNIVERSAL_IDENTIFIER = '37cdf23d-e49c-4010-b1da-603ba89f2a9c';
export const SEO_AUDIT_SCORE_FIELD_UNIVERSAL_IDENTIFIER = '96b02e1e-94af-4263-b080-fd46e202401a';
export const SEO_AUDIT_GRADE_FIELD_UNIVERSAL_IDENTIFIER = '3a84be13-19ed-4b88-852b-b8e35e4c5721';
export const SEO_AUDIT_PAGES_CRAWLED_FIELD_UNIVERSAL_IDENTIFIER = '82e5150c-9bde-4496-b04f-1629f6bd0795';
export const SEO_AUDIT_AREA_SCORES_FIELD_UNIVERSAL_IDENTIFIER = '5a834691-0c10-4a62-89e5-0030acf66d54';
export const SEO_AUDIT_REPORT_MARKDOWN_FIELD_UNIVERSAL_IDENTIFIER = 'bb19ce12-d0c8-4aef-a9d3-494c0bdc23ac';
export const SEO_AUDIT_STARTED_AT_FIELD_UNIVERSAL_IDENTIFIER = 'b5386a5e-9b13-4201-a581-230e19bba950';
export const SEO_AUDIT_FINISHED_AT_FIELD_UNIVERSAL_IDENTIFIER = 'b8efe40f-7fcf-4203-8449-b50cdcbaf4e0';
export const SEO_AUDIT_EXCEL_FILE_FIELD_UNIVERSAL_IDENTIFIER = '547bb5ba-cad7-4490-a4b2-2d964b8acaab';
export const SEO_AUDIT_PDF_FILE_FIELD_UNIVERSAL_IDENTIFIER = '8f7ca6a7-13b0-4fdd-b8da-e825421db48a';
export const SEO_AUDIT_FAILURE_REASON_FIELD_UNIVERSAL_IDENTIFIER = '91288421-a54e-473d-ba2b-b1483c875e23';

export default defineObject({
  universalIdentifier: SEO_AUDIT_UNIVERSAL_IDENTIFIER,
  nameSingular: 'seoAudit',
  namePlural: 'seoAudits',
  labelSingular: 'SEO audit',
  labelPlural: 'SEO audits',
  description: 'A website SEO audit with score, findings and action list',
  icon: 'IconReportSearch',
  labelIdentifierFieldMetadataUniversalIdentifier:
    SEO_AUDIT_NAME_FIELD_UNIVERSAL_IDENTIFIER,
  fields: [
    {
      universalIdentifier: SEO_AUDIT_NAME_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'name',
      label: 'Name',
      description: 'Filled automatically with the domain and date',
      icon: 'IconAbc',
      isNullable: true,
    },
    {
      universalIdentifier: SEO_AUDIT_DOMAIN_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'domain',
      label: 'Domain',
      description: 'Homepage URL or domain to audit, for example example.com',
      icon: 'IconWorld',
    },
    {
      universalIdentifier: SEO_AUDIT_STATUS_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.SELECT,
      name: 'status',
      label: 'Status',
      icon: 'IconProgress',
      defaultValue: `'${SEO_AUDIT_STATUS.QUEUED}'`,
      options: buildSelectOptions([
        { id: '3a9a58bf-f55b-4d3f-84e7-d0db6336fbc0', value: SEO_AUDIT_STATUS.QUEUED, label: 'Queued', color: 'blue' },
        { id: 'f0cc033f-29d4-41eb-b4df-040155921e9a', value: SEO_AUDIT_STATUS.RUNNING, label: 'Running', color: 'purple' },
        { id: '462e73eb-96fc-4259-a254-8a33f97b2e63', value: SEO_AUDIT_STATUS.DONE, label: 'Done', color: 'green' },
        { id: '7787e472-4669-4497-8f6a-7b555010017c', value: SEO_AUDIT_STATUS.FAILED, label: 'Failed', color: 'red' },
      ]),
    },
    {
      universalIdentifier: SEO_AUDIT_LANGUAGE_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.SELECT,
      name: 'language',
      label: 'Report language',
      description: 'Leave empty to use the default language from the app settings',
      icon: 'IconLanguage',
      isNullable: true,
      options: buildSelectOptions([
        { id: '2ee27b38-140f-4a02-a31e-1a45d830032d', value: SEO_AUDIT_LANGUAGE.DE, label: 'German', color: 'yellow' },
        { id: '66e21c29-53e6-44eb-86e0-9072d317f58c', value: SEO_AUDIT_LANGUAGE.EN, label: 'English', color: 'blue' },
      ]),
    },
    {
      universalIdentifier: SEO_AUDIT_SCORE_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.NUMBER,
      name: 'score',
      label: 'Score',
      description: 'Overall score from 0 to 100',
      icon: 'IconGauge',
      isNullable: true,
    },
    {
      universalIdentifier: SEO_AUDIT_GRADE_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'grade',
      label: 'Grade',
      icon: 'IconAward',
      isNullable: true,
    },
    {
      universalIdentifier: SEO_AUDIT_PAGES_CRAWLED_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.NUMBER,
      name: 'pagesCrawled',
      label: 'Pages crawled',
      icon: 'IconFiles',
      isNullable: true,
    },
    {
      universalIdentifier: SEO_AUDIT_AREA_SCORES_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.RAW_JSON,
      name: 'areaScores',
      label: 'Area scores',
      description: 'Score per audit area, keyed by area',
      icon: 'IconChartRadar',
      isNullable: true,
    },
    {
      universalIdentifier:
        SEO_AUDIT_REPORT_MARKDOWN_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'reportMarkdown',
      label: 'Report (Markdown)',
      description: 'Full report an agent can read and work through',
      icon: 'IconFileDescription',
      isNullable: true,
    },
    {
      universalIdentifier: SEO_AUDIT_STARTED_AT_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.DATE_TIME,
      name: 'startedAt',
      label: 'Started at',
      icon: 'IconPlayerPlay',
      isNullable: true,
    },
    {
      universalIdentifier: SEO_AUDIT_FINISHED_AT_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.DATE_TIME,
      name: 'finishedAt',
      label: 'Finished at',
      icon: 'IconFlagCheck',
      isNullable: true,
    },
    {
      universalIdentifier: SEO_AUDIT_FAILURE_REASON_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'failureReason',
      label: 'Failure reason',
      icon: 'IconAlertTriangle',
      isNullable: true,
    },
    {
      universalIdentifier: '86c85cbb-15e1-48d8-aa4b-a327657c5f14',
      type: FieldType.NUMBER,
      name: 'organicKeywordCount',
      label: 'Ranking keywords',
      description: 'Keywords the website ranks for on Google, from DataForSEO',
      icon: 'IconSearch',
      isNullable: true,
    },
    {
      universalIdentifier: 'dba47788-b7b4-4cec-92b8-2cbb2bfb740f',
      type: FieldType.NUMBER,
      name: 'estimatedMonthlyTraffic',
      label: 'Estimated monthly traffic',
      icon: 'IconUsers',
      isNullable: true,
    },
    {
      universalIdentifier: 'b6d59292-af29-48c3-bb16-5d6bd0786240',
      type: FieldType.NUMBER,
      name: 'backlinkCount',
      label: 'Backlinks',
      icon: 'IconLink',
      isNullable: true,
    },
    {
      universalIdentifier: 'ec92258a-2335-4f03-a65f-04018b237535',
      type: FieldType.NUMBER,
      name: 'referringDomainCount',
      label: 'Referring domains',
      icon: 'IconWorld',
      isNullable: true,
    },
    {
      universalIdentifier: '31c09d6e-ade0-4922-b191-71bd2b9dee50',
      type: FieldType.NUMBER,
      name: 'mobilePerformanceScore',
      label: 'Mobile performance score',
      description: 'Lighthouse performance score of the homepage on mobile, 0 to 100',
      icon: 'IconGauge',
      isNullable: true,
    },
    {
      universalIdentifier: '28075b8a-81c3-4d16-95d6-b43dd5bc570a',
      type: FieldType.NUMBER,
      name: 'mobileLcpMs',
      label: 'Mobile LCP (ms)',
      description: 'Largest Contentful Paint of the homepage on mobile. Good is under 2500 ms.',
      icon: 'IconClock',
      isNullable: true,
    },
    {
      universalIdentifier: 'd641d7d8-7778-4018-9b73-61d51e26b70b',
      type: FieldType.NUMBER,
      name: 'mobileCls',
      label: 'Mobile CLS',
      description: 'Cumulative Layout Shift of the homepage on mobile. Good is under 0.1.',
      icon: 'IconArrowsMove',
      isNullable: true,
    },
    {
      universalIdentifier: '2e99e3ae-8651-44e8-877b-e88514502f52',
      type: FieldType.NUMBER,
      name: 'mobileTbtMs',
      label: 'Mobile TBT (ms)',
      description: 'Total Blocking Time of the homepage on mobile. Good is under 200 ms.',
      icon: 'IconHourglass',
      isNullable: true,
    },
    {
      universalIdentifier: '5cccf6c5-4ca6-4594-a01d-cabca5fee803',
      type: FieldType.RAW_JSON,
      name: 'competitors',
      label: 'Competitors',
      icon: 'IconUsersGroup',
      isNullable: true,
    },
    {
      universalIdentifier: '9ff0bbeb-e620-4d90-b99c-60fff218006f',
      type: FieldType.NUMBER,
      name: 'marketDataCostUsd',
      label: 'DataForSEO cost (USD)',
      description: 'What the market data of this audit cost at DataForSEO',
      icon: 'IconCoin',
      isNullable: true,
    },
    {
      universalIdentifier: '7e05888b-03c5-41a0-9fe3-514014d45d5e',
      type: FieldType.TEXT,
      name: 'marketDataNotes',
      label: 'Market data notes',
      description: 'Requests that failed or were skipped',
      icon: 'IconInfoCircle',
      isNullable: true,
    },
    {
      universalIdentifier: '069e7a72-bb8c-447a-bdcd-505ae49ffc74',
      type: FieldType.NUMBER,
      name: 'aiPresenceRate',
      label: 'AI presence (0-1)',
      description: 'Share of AI answers that name the website: cited counts 1, mentioned counts 0.5',
      icon: 'IconRobot',
      isNullable: true,
    },
    {
      universalIdentifier: 'fb89be9f-dd82-4041-adc3-3ce275d3a95b',
      type: FieldType.NUMBER,
      name: 'aiQueriesTested',
      label: 'AI questions asked',
      description: 'Customer questions with at least one answer that could be judged',
      icon: 'IconMessageQuestion',
      isNullable: true,
    },
    {
      universalIdentifier: '60cb4212-090b-45a8-8c36-84e74ea1fd00',
      type: FieldType.RAW_JSON,
      name: 'aiUsage',
      label: 'AI usage',
      description: 'Tokens per model used by this audit, to work out its cost',
      icon: 'IconCoin',
      isNullable: true,
    },
    {
      universalIdentifier: 'a15e094e-48fa-4b3a-a107-729b28ebe09a',
      type: FieldType.RAW_JSON,
      name: 'aiVisibility',
      label: 'AI answers',
      description: 'Per question: whether ChatGPT, Perplexity and Gemini cited or mentioned the website, and who they named instead',
      icon: 'IconBrain',
      isNullable: true,
    },
    {
      universalIdentifier: '3062ded5-bde8-4c73-9d9e-7647e4e99aa4',
      type: FieldType.TEXT,
      name: 'reportHtml',
      label: 'Report (HTML)',
      description: 'Print-ready report page, source of the PDF',
      icon: 'IconFileTypeHtml',
      isNullable: true,
    },
    {
      universalIdentifier: '5e58c95a-f456-41b1-926d-01eec9f8fd6e',
      type: FieldType.TEXT,
      name: 'reportUrl',
      label: 'Report link',
      description: 'Share this link with the client. Open it and choose Save as PDF.',
      icon: 'IconExternalLink',
      isNullable: true,
    },
    {
      universalIdentifier: '5ccee369-55dc-4e4c-8521-07dba2f1dc6a',
      type: FieldType.TEXT,
      name: 'shareToken',
      label: 'Share token',
      description: 'Part of the report link. Clear it to disable the link.',
      icon: 'IconKey',
      isNullable: true,
    },
    {
      universalIdentifier: SEO_AUDIT_EXCEL_FILE_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.FILES,
      name: 'excelFile',
      label: 'Excel',
      description: 'Action list, pages, keywords and backlinks as a spreadsheet',
      icon: 'IconFileSpreadsheet',
      universalSettings: { maxNumberOfValues: 1 },
    },
    {
      universalIdentifier: SEO_AUDIT_PDF_FILE_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.FILES,
      name: 'pdfFile',
      label: 'PDF',
      description: 'Client-ready report, rendered from the HTML page',
      icon: 'IconFileTypePdf',
      universalSettings: { maxNumberOfValues: 1 },
    },
    {
      universalIdentifier: 'fd556651-8eab-4445-849d-5917fdb93d3c',
      type: FieldType.TEXT,
      name: 'exportNotes',
      label: 'Export notes',
      description: 'Exports that failed or were skipped',
      icon: 'IconInfoCircle',
      isNullable: true,
    },
  ],
});
