// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/expertise": {
    params: {};
  };
  "/expertise/:slug": {
    params: {
      "slug": string;
    };
  };
  "/expertise/:slug/:subSlug": {
    params: {
      "slug": string;
      "subSlug": string;
    };
  };
  "/work": {
    params: {};
  };
  "/work/:slug": {
    params: {
      "slug": string;
    };
  };
  "/approach": {
    params: {};
  };
  "/insights": {
    params: {};
  };
  "/insights/:slug": {
    params: {
      "slug": string;
    };
  };
  "/about": {
    params: {};
  };
  "/contact": {
    params: {};
  };
  "/sitemap.xml": {
    params: {};
  };
  "/robots.txt": {
    params: {};
  };
  "/llms.txt": {
    params: {};
  };
  "/llms-full.txt": {
    params: {};
  };
  "/api/health": {
    params: {};
  };
  "/api/contact": {
    params: {};
  };
  "/api/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/expertise" | "/expertise/:slug" | "/expertise/:slug/:subSlug" | "/work" | "/work/:slug" | "/approach" | "/insights" | "/insights/:slug" | "/about" | "/contact" | "/sitemap.xml" | "/robots.txt" | "/llms.txt" | "/llms-full.txt" | "/api/health" | "/api/contact" | "/api/*";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/expertise.tsx": {
    id: "routes/expertise";
    page: "/expertise";
  };
  "routes/expertise.$slug.tsx": {
    id: "routes/expertise.$slug";
    page: "/expertise/:slug";
  };
  "routes/expertise.$slug.$subSlug.tsx": {
    id: "routes/expertise.$slug.$subSlug";
    page: "/expertise/:slug/:subSlug";
  };
  "routes/work.tsx": {
    id: "routes/work";
    page: "/work";
  };
  "routes/work.$slug.tsx": {
    id: "routes/work.$slug";
    page: "/work/:slug";
  };
  "routes/approach.tsx": {
    id: "routes/approach";
    page: "/approach";
  };
  "routes/insights.tsx": {
    id: "routes/insights";
    page: "/insights";
  };
  "routes/insights.$slug.tsx": {
    id: "routes/insights.$slug";
    page: "/insights/:slug";
  };
  "routes/about.tsx": {
    id: "routes/about";
    page: "/about";
  };
  "routes/contact.tsx": {
    id: "routes/contact";
    page: "/contact";
  };
  "routes/sitemap.xml.ts": {
    id: "routes/sitemap.xml";
    page: "/sitemap.xml";
  };
  "routes/robots.txt.ts": {
    id: "routes/robots.txt";
    page: "/robots.txt";
  };
  "routes/llms.txt.ts": {
    id: "routes/llms.txt";
    page: "/llms.txt";
  };
  "routes/llms-full.txt.ts": {
    id: "routes/llms-full.txt";
    page: "/llms-full.txt";
  };
  "routes/api.health.ts": {
    id: "routes/api.health";
    page: "/api/health";
  };
  "routes/api.contact.ts": {
    id: "routes/api.contact";
    page: "/api/contact";
  };
  "routes/api.$.ts": {
    id: "routes/api.$";
    page: "/api/*";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "routes/home": typeof import("./src/routes/home.tsx");
  "routes/expertise": typeof import("./src/routes/expertise.tsx");
  "routes/expertise.$slug": typeof import("./src/routes/expertise.$slug.tsx");
  "routes/expertise.$slug.$subSlug": typeof import("./src/routes/expertise.$slug.$subSlug.tsx");
  "routes/work": typeof import("./src/routes/work.tsx");
  "routes/work.$slug": typeof import("./src/routes/work.$slug.tsx");
  "routes/approach": typeof import("./src/routes/approach.tsx");
  "routes/insights": typeof import("./src/routes/insights.tsx");
  "routes/insights.$slug": typeof import("./src/routes/insights.$slug.tsx");
  "routes/about": typeof import("./src/routes/about.tsx");
  "routes/contact": typeof import("./src/routes/contact.tsx");
  "routes/sitemap.xml": typeof import("./src/routes/sitemap.xml.ts");
  "routes/robots.txt": typeof import("./src/routes/robots.txt.ts");
  "routes/llms.txt": typeof import("./src/routes/llms.txt.ts");
  "routes/llms-full.txt": typeof import("./src/routes/llms-full.txt.ts");
  "routes/api.health": typeof import("./src/routes/api.health.ts");
  "routes/api.contact": typeof import("./src/routes/api.contact.ts");
  "routes/api.$": typeof import("./src/routes/api.$.ts");
};