export const ANTHROPIC_API_KEY_VARIABLE_KEY = 'ANTHROPIC_API_KEY';
export const DEFAULT_LANGUAGE_VARIABLE_KEY = 'SEO_AUDIT_DEFAULT_LANGUAGE';
export const MAX_PAGES_VARIABLE_KEY = 'SEO_AUDIT_MAX_PAGES';
export const DATAFORSEO_LOGIN_VARIABLE_KEY = 'DATAFORSEO_LOGIN';
export const DATAFORSEO_PASSWORD_VARIABLE_KEY = 'DATAFORSEO_PASSWORD';
export const MARKET_VARIABLE_KEY = 'SEO_AUDIT_MARKET';
