import { type AuditLanguage } from 'src/types/audit-language';
import { type ExcelLabels } from 'src/types/excel-labels';

export const EXCEL_LABELS: Record<AuditLanguage, ExcelLabels> = {
  DE: {
    sheets: {
      overview: 'Übersicht',
      actions: 'Maßnahmen',
      pages: 'Seiten',
      keywords: 'Keywords',
      backlinks: 'Backlinks',
      competitors: 'Wettbewerber',
      review: 'Prüfliste',
    },
    overview: {
      domain: 'Domain',
      generatedOn: 'Erstellt am',
      score: 'Gesamtscore',
      grade: 'Note',
      pages: 'Seiten geprüft',
      tasks: 'Maßnahmen',
      area: 'Bereich',
      areaScore: 'Score',
      band: 'Einstufung',
      mobilePerformanceScore: 'Mobil: Performance-Score',
      mobileLcp: 'Mobil: LCP (ms)',
      mobileCls: 'Mobil: CLS',
      mobileTbt: 'Mobil: TBT (ms)',
    },
    actions: {
      number: 'Nr.',
      priority: 'Priorität',
      effort: 'Aufwand',
      area: 'Bereich',
      source: 'Quelle',
      task: 'Maßnahme',
      recommendation: 'Empfehlung',
      affectedCount: 'Betroffene URLs',
      affectedUrls: 'URLs',
      status: 'Status',
    },
    statuses: ['Offen', 'In Arbeit', 'Erledigt', 'Wird nicht umgesetzt'],
    pages: {
      url: 'URL',
      statusCode: 'Status',
      responseTime: 'Antwortzeit (ms)',
      title: 'Title',
      words: 'Wörter',
      headings: 'H1',
      imagesWithoutAlt: 'Bilder ohne Alt-Text',
      structuredData: 'Strukturierte Daten',
      pageType: 'Seitentyp',
      intent: 'Suchintention',
      helpfulness: 'Hilfreichkeit (1-5)',
      specificity: 'Konkretheit (1-5)',
      trust: 'Vertrauen (1-5)',
      confidence: 'Konfidenz (0-1)',
      needsReview: 'Prüfen',
    },
    keywords: {
      keyword: 'Keyword',
      position: 'Platz',
      volume: 'Suchen pro Monat',
      traffic: 'Geschätzte Besucher',
      category: 'Kategorie',
      relevance: 'Relevanz (0-1)',
      confidence: 'Konfidenz (0-1)',
      needsReview: 'Prüfen',
      page: 'Seite',
    },
    backlinks: {
      metric: 'Kennzahl',
      value: 'Wert',
      backlinks: 'Backlinks',
      referringDomains: 'Verweisende Domains',
      brokenPages: 'Verlinkte Seiten, die nicht mehr existieren',
      brokenTargetsHeading: 'Backlinks auf nicht mehr existierende Seiten',
      backlinksColumn: 'Backlinks',
      domainsColumn: 'Domains',
    },
    competitors: {
      domain: 'Domain',
      commonKeywords: 'Gemeinsame Keywords',
      traffic: 'Geschätzte Besucher',
    },
    review: { type: 'Art', item: 'Eintrag', page: 'Seite', keyword: 'Keyword' },
    yes: 'Ja',
    no: 'Nein',
  },
  EN: {
    sheets: {
      overview: 'Overview',
      actions: 'Actions',
      pages: 'Pages',
      keywords: 'Keywords',
      backlinks: 'Backlinks',
      competitors: 'Competitors',
      review: 'To review',
    },
    overview: {
      domain: 'Domain',
      generatedOn: 'Generated on',
      score: 'Overall score',
      grade: 'Grade',
      pages: 'Pages checked',
      tasks: 'Actions',
      area: 'Area',
      areaScore: 'Score',
      band: 'Rating',
      mobilePerformanceScore: 'Mobile performance score',
      mobileLcp: 'Mobile LCP (ms)',
      mobileCls: 'Mobile CLS',
      mobileTbt: 'Mobile TBT (ms)',
    },
    actions: {
      number: 'No.',
      priority: 'Priority',
      effort: 'Effort',
      area: 'Area',
      source: 'Source',
      task: 'Action',
      recommendation: 'Recommendation',
      affectedCount: 'Affected URLs',
      affectedUrls: 'URLs',
      status: 'Status',
    },
    statuses: ['Open', 'In progress', 'Done', "Won't fix"],
    pages: {
      url: 'URL',
      statusCode: 'Status',
      responseTime: 'Response time (ms)',
      title: 'Title',
      words: 'Words',
      headings: 'H1',
      imagesWithoutAlt: 'Images without alt text',
      structuredData: 'Structured data',
      pageType: 'Page type',
      intent: 'Search intent',
      helpfulness: 'Helpfulness (1-5)',
      specificity: 'Specificity (1-5)',
      trust: 'Trust (1-5)',
      confidence: 'Confidence (0-1)',
      needsReview: 'Review',
    },
    keywords: {
      keyword: 'Keyword',
      position: 'Position',
      volume: 'Searches per month',
      traffic: 'Estimated visitors',
      category: 'Category',
      relevance: 'Relevance (0-1)',
      confidence: 'Confidence (0-1)',
      needsReview: 'Review',
      page: 'Page',
    },
    backlinks: {
      metric: 'Metric',
      value: 'Value',
      backlinks: 'Backlinks',
      referringDomains: 'Referring domains',
      brokenPages: 'Linked pages that no longer exist',
      brokenTargetsHeading: 'Backlinks pointing to pages that no longer exist',
      backlinksColumn: 'Backlinks',
      domainsColumn: 'Domains',
    },
    competitors: {
      domain: 'Domain',
      commonKeywords: 'Shared keywords',
      traffic: 'Estimated visitors',
    },
    review: { type: 'Type', item: 'Entry', page: 'Page', keyword: 'Keyword' },
    yes: 'Yes',
    no: 'No',
  },
};
