import { type AuditLanguage } from 'src/types/audit-language';
import { type ReportLabels } from 'src/types/report-labels';

export const REPORT_LABELS: Record<AuditLanguage, ReportLabels> = {
  DE: {
    title: 'SEO-Audit',
    generatedOn: 'Erstellt am',
    score: 'Gesamtscore',
    grade: 'Note',
    pagesChecked: 'Seiten geprüft',
    areasHeading: 'Bereiche',
    areaColumn: 'Bereich',
    scoreColumn: 'Score',
    summaryHeading: 'Zusammenfassung',
    strongestArea: 'Stärkster Bereich',
    weakestArea: 'Schwächster Bereich',
    taskCount: 'Maßnahmen insgesamt',
    criticalCount: 'davon kritisch',
    noTasks: 'Es wurden keine Maßnahmen gefunden.',
    tasksHeading: 'Maßnahmenliste',
    horizonWeek: 'Diese Woche',
    horizonMonth: 'Diesen Monat',
    horizonQuarter: 'Dieses Quartal',
    priorityColumn: 'Priorität',
    effortColumn: 'Aufwand',
    sourceColumn: 'Quelle',
    taskColumn: 'Maßnahme',
    affectedUrls: 'Betroffene URLs',
    moreUrls: 'weitere',
    reviewHeading: 'Bitte manuell prüfen',
    reviewIntro:
      'Bei diesen Seiten war die automatische Bewertung unsicher. Sie fließen nicht in die Maßnahmen ein.',
    methodologyHeading: 'Methodik',
    methodology:
      'Gemessen (Quelle "Regel"): Statuscodes, Titles, Descriptions, Überschriften, Links, HTTPS, Antwortzeit und strukturierte Daten werden vom Code gezählt und nicht geschätzt. Beurteilt (Quelle "Klassifikator"): Seitentyp, Suchintention, Hilfreichkeit, Konkretheit und Vertrauen bewertet ein Sprachmodell. Die Konfidenz ist eine Selbsteinschätzung des Modells und keine berechnete Wahrscheinlichkeit. Rankings, Suchvolumen, Backlinks und Wettbewerber stammen von DataForSEO. Der Sichtbarkeits-Score gewichtet die Platzierungen relevanter Keywords nach Suchvolumen. Die Ladegeschwindigkeit der Startseite auf dem Handy misst Lighthouse über DataForSEO. Die KI-Bereitschaft prüft robots.txt, llms.txt und strukturierte Daten und misst nicht, ob KI-Systeme die Website tatsächlich nennen.',
    contentNotAssessed:
      'Die Inhaltsqualität wurde nicht bewertet, weil kein Klassifikator konfiguriert war. Der Gesamtscore beruht nur auf gemessenen Regeln.',
    marketDataNotConfigured:
      'Rankings, Keywords und Backlinks fehlen, weil DataForSEO nicht eingerichtet ist. Du kannst es im Setup-Tab ergänzen.',
    marketHeading: 'Sichtbarkeit und Markt',
    marketNotes: 'Nicht verfügbar',
    lighthouseHeading: 'Ladegeschwindigkeit auf dem Handy',
    performanceScore: 'Performance-Score',
    largestContentfulPaint: 'Hauptinhalt sichtbar (LCP)',
    layoutShift: 'Layoutverschiebung (CLS)',
    blockingTime: 'Blockierzeit (TBT)',
    aiReadinessHeading: 'KI-Bereitschaft',
    aiReadinessIntro:
      'Zeigt, ob KI-Systeme die Website lesen und einem Unternehmen zuordnen können. Gemessen aus robots.txt, llms.txt und dem Markup der Seiten. Ob die Website in KI-Antworten genannt wird, zeigt diese Prüfung nicht.',
    aiReadinessCheckColumn: 'Prüfung',
    aiReadinessStatusColumn: 'Status',
    crawlerAccess: 'Crawler-Zugriff',
    crawlerAllowed: 'erlaubt',
    crawlerBlocked: 'gesperrt',
    present: 'vorhanden',
    missing: 'fehlt',
    llmsTxt: 'llms.txt',
    organizationMarkup: 'Organisations-Markup auf der Startseite',
    faqMarkup: 'FAQ-Markup',
    aiVisibilityHeading: 'KI-Antworten',
    aiVisibilityIntro:
      'Typische Kundenfragen, gestellt an KI-Assistenten, die im Web suchen. Die Antworten schwanken von Lauf zu Lauf, die Messung ist eine Stichprobe.',
    aiVisibilityPresence: 'Anteil der Antworten, die die Website nennen',
    aiVisibilityTestedOn: 'Gemessen am',
    questionColumn: 'Frage',
    namedInsteadColumn: 'Stattdessen genannt',
    statusCited: 'zitiert',
    statusMentioned: 'erwähnt',
    statusAbsent: 'fehlt',
    statusUnknown: 'n/v',
    keywordsTotal: 'Keywords mit Google-Ranking',
    trafficEstimate: 'Geschätzte Besucher pro Monat',
    positionsHeading: 'Verteilung der Platzierungen',
    opportunitiesHeading: 'Keyword-Chancen',
    keywordColumn: 'Keyword',
    positionColumn: 'Platz',
    volumeColumn: 'Suchen pro Monat',
    pageColumn: 'Seite',
    notRelevantHeading: 'Aussortierte Rankings',
    notRelevantIntro:
      'Für diese Keywords rankt die Website, sie passen aber nicht zum Unternehmen und bringen keine Kunden.',
    backlinksHeading: 'Backlinks',
    backlinksTotal: 'Backlinks',
    referringDomains: 'Verweisende Domains',
    brokenBacklinkPages: 'Verlinkte Seiten, die nicht mehr existieren',
    competitorsHeading: 'Wettbewerber',
    domainColumn: 'Domain',
    commonKeywordsColumn: 'Gemeinsame Keywords',
    trafficColumn: 'Geschätzte Besucher',
    keywordCategories: { QUICK_WIN: 'Platz 4 bis 10', NEAR_PAGE_ONE: 'Platz 11 bis 30' },
    areas: {
      CRAWLABILITY: 'Crawling',
      ON_PAGE: 'On-Page',
      CONTENT_QUALITY: 'Inhaltsqualität',
      LINKS: 'Links',
      STRUCTURED_DATA: 'Strukturierte Daten',
      PERFORMANCE: 'Ladezeit',
      SECURITY: 'Sicherheit',
      VISIBILITY: 'Sichtbarkeit',
      AI_VISIBILITY: 'KI-Sichtbarkeit',
    },
    priorities: {
      CRITICAL: 'Kritisch',
      HIGH: 'Hoch',
      MEDIUM: 'Mittel',
      LOW: 'Niedrig',
    },
    efforts: { LOW: 'Gering', MEDIUM: 'Mittel', HIGH: 'Hoch' },
    sources: { RULE: 'Regel', CLASSIFIER: 'Klassifikator' },
  },
  EN: {
    title: 'SEO audit',
    generatedOn: 'Generated on',
    score: 'Overall score',
    grade: 'Grade',
    pagesChecked: 'pages checked',
    areasHeading: 'Areas',
    areaColumn: 'Area',
    scoreColumn: 'Score',
    summaryHeading: 'Summary',
    strongestArea: 'Strongest area',
    weakestArea: 'Weakest area',
    taskCount: 'Total actions',
    criticalCount: 'of which critical',
    noTasks: 'No actions were found.',
    tasksHeading: 'Action list',
    horizonWeek: 'This week',
    horizonMonth: 'This month',
    horizonQuarter: 'This quarter',
    priorityColumn: 'Priority',
    effortColumn: 'Effort',
    sourceColumn: 'Source',
    taskColumn: 'Action',
    affectedUrls: 'Affected URLs',
    moreUrls: 'more',
    reviewHeading: 'Please review manually',
    reviewIntro:
      'The automatic assessment was unsure about these pages. They do not feed into the actions.',
    methodologyHeading: 'Methodology',
    methodology:
      'Measured (source "Rule"): status codes, titles, descriptions, headings, links, HTTPS, response time and structured data are counted by code, never estimated. Judged (source "Classifier"): page type, search intent, helpfulness, specificity and trust are rated by a language model. Confidence is the model self-assessment, not a computed probability. Rankings, search volume, backlinks and competitors come from DataForSEO. The visibility score weights the positions of relevant keywords by search volume. The mobile loading speed of the homepage is measured by Lighthouse through DataForSEO. The AI readiness checks robots.txt, llms.txt and structured data and does not measure whether AI systems actually mention the website.',
    contentNotAssessed:
      'Content quality was not assessed because no classifier was configured. The overall score only reflects measured rules.',
    marketDataNotConfigured:
      'Rankings, keywords and backlinks are missing because DataForSEO is not set up. You can add it in the Setup tab.',
    marketHeading: 'Visibility and market',
    marketNotes: 'Not available',
    lighthouseHeading: 'Mobile loading speed',
    performanceScore: 'Performance score',
    largestContentfulPaint: 'Main content visible (LCP)',
    layoutShift: 'Layout shift (CLS)',
    blockingTime: 'Blocking time (TBT)',
    aiReadinessHeading: 'AI readiness',
    aiReadinessIntro:
      'Shows whether AI systems can read the website and attribute it to a business. Measured from robots.txt, llms.txt and the markup of the pages. This check does not show whether the website is mentioned in AI answers.',
    aiReadinessCheckColumn: 'Check',
    aiReadinessStatusColumn: 'Status',
    crawlerAccess: 'Crawler access',
    crawlerAllowed: 'allowed',
    crawlerBlocked: 'blocked',
    present: 'present',
    missing: 'missing',
    llmsTxt: 'llms.txt',
    organizationMarkup: 'Organization markup on the homepage',
    faqMarkup: 'FAQ markup',
    aiVisibilityHeading: 'AI answers',
    aiVisibilityIntro:
      'Typical customer questions put to AI assistants that search the web. The answers vary from run to run, so the measurement is a sample.',
    aiVisibilityPresence: 'Share of answers that name the website',
    aiVisibilityTestedOn: 'Measured on',
    questionColumn: 'Question',
    namedInsteadColumn: 'Named instead',
    statusCited: 'cited',
    statusMentioned: 'mentioned',
    statusAbsent: 'absent',
    statusUnknown: 'n/a',
    keywordsTotal: 'Keywords ranking on Google',
    trafficEstimate: 'Estimated monthly visitors',
    positionsHeading: 'Position distribution',
    opportunitiesHeading: 'Keyword opportunities',
    keywordColumn: 'Keyword',
    positionColumn: 'Position',
    volumeColumn: 'Searches per month',
    pageColumn: 'Page',
    notRelevantHeading: 'Filtered out rankings',
    notRelevantIntro:
      'The website ranks for these keywords, but they do not fit the business and bring no customers.',
    backlinksHeading: 'Backlinks',
    backlinksTotal: 'Backlinks',
    referringDomains: 'Referring domains',
    brokenBacklinkPages: 'Linked pages that no longer exist',
    competitorsHeading: 'Competitors',
    domainColumn: 'Domain',
    commonKeywordsColumn: 'Shared keywords',
    trafficColumn: 'Estimated visitors',
    keywordCategories: { QUICK_WIN: 'Positions 4 to 10', NEAR_PAGE_ONE: 'Positions 11 to 30' },
    areas: {
      CRAWLABILITY: 'Crawlability',
      ON_PAGE: 'On-page',
      CONTENT_QUALITY: 'Content quality',
      LINKS: 'Links',
      STRUCTURED_DATA: 'Structured data',
      PERFORMANCE: 'Performance',
      SECURITY: 'Security',
      VISIBILITY: 'Visibility',
      AI_VISIBILITY: 'AI visibility',
    },
    priorities: {
      CRITICAL: 'Critical',
      HIGH: 'High',
      MEDIUM: 'Medium',
      LOW: 'Low',
    },
    efforts: { LOW: 'Low', MEDIUM: 'Medium', HIGH: 'High' },
    sources: { RULE: 'Rule', CLASSIFIER: 'Classifier' },
  },
};
