import { type AuditLanguage } from 'src/types/audit-language';
import { type ReportDesignLabels } from 'src/types/report-design-labels';

export const REPORT_DESIGN_LABELS: Record<AuditLanguage, ReportDesignLabels> = {
  DE: {
    heroEyebrow: (domain, date) => `Audit · ${domain} · ${date}`,
    heroHeadline: 'SEO-Audit',
    metaPages: 'Geprüft',
    metaDate: 'Stand',
    metaEngines: 'KI-Engines',
    gaugeCaption: 'GESAMTSCORE / 100',
    gradeWord: 'Note',
    rulesOnlyAverage: (rulesOnly) => `Nur gemessene Regeln: ${rulesOnly}`,
    marquee: ['Technical SEO', 'AI Visibility', 'Content', 'Entity & Schema', 'Core Web Vitals', 'Citations'],
    openReport: 'Als PDF speichern',
    sections: {
      summary: { eyebrow: 'Das Wichtigste', plain: 'Das Wichtigste', accent: 'in Kürze.' },
      scorecard: { eyebrow: 'Scorecard', plain: 'Die Bereiche.', accent: 'Ein Bild.' },
      ai: { eyebrow: 'KI-Sichtbarkeit', plain: 'Wenn Kunden', accent: 'die KI fragen.' },
      findings: { eyebrow: 'Die größten Hebel', plain: 'Hier', accent: 'liegt der Hebel.' },
      pages: { eyebrow: 'Seiten im Detail', plain: 'Jede Seite', accent: 'einzeln bewertet.' },
      market: { eyebrow: 'Sichtbarkeit und Markt', plain: 'Sichtbar', accent: 'im Markt.' },
      opportunities: { eyebrow: 'Chancen', plain: 'Hier fehlt', accent: 'eine Seite.' },
      strengths: { eyebrow: 'Was bereits funktioniert', plain: 'Gute', accent: 'Basis.' },
      roadmap: { eyebrow: 'Der Weg', plain: 'Der Weg', accent: 'in drei Schritten.' },
      method: { eyebrow: 'Methodik und Transparenz', plain: 'So haben wir geprüft', accent: '' },
    },
    strengthTitles: {
      STRONG_AREAS: 'Starke Bereiche',
      TOP_RANKINGS: 'Top-Rankings',
      HELPFUL_PAGES: 'Hilfreiche Seiten',
      AI_READINESS: 'KI-Bereitschaft',
      AI_PRESENCE: 'In KI-Antworten genannt',
    },
    scorecardLead:
      'Jeder Bereich wird einzeln bewertet und mit seinem Gewicht in den Gesamtscore übernommen.',
    tasksInArea: (count) => `${count} ${count === 1 ? 'Maßnahme' : 'Maßnahmen'} offen`,
    noTasksInArea: 'Keine Maßnahme nötig',
    impactEyebrow: 'Inhaltsbewertung',
    impactTitle: (rulesOnly, score) =>
      `Allein nach den gemessenen Regeln läge der Score bei ${rulesOnly}. Mit der Bewertung von Inhalt und Keywords liegt er bei ${score}.`,
    impactHint: 'Ein rein technischer Audit sieht diesen Unterschied nicht.',
    summaryBlockers: 'Was bremst',
    summaryStrengths: 'Was gut läuft',
    evidence: 'Beleg',
    recommendation: 'Lösung',
    affected: 'Betroffen',
    effortLabel: 'Aufwand',
    sourceLabel: 'Quelle',
    horizonLabel: 'Horizont',
    moreMeasures: 'Weitere Maßnahmen',
    findingsLead: (shown, total) =>
      total > shown
        ? `Die ${shown} wichtigsten von ${total} Maßnahmen, jeweils mit Beleg und Lösung. Alle weiteren stehen darunter.`
        : `Alle ${total} Maßnahmen, jeweils mit Beleg und Lösung.`,
    aiReadinessChips: 'KI-Bereitschaft',
    aiPresence: 'Anteil der Antworten, die die Website nennen',
    aiTestedOn: (date) => `Getestet am ${date}. Ergebnisse können je Sitzung variieren.`,
    pagesLead:
      'Jede Seite wurde einzeln bewertet. 1 ist schwach, 5 ist stark. Bei Unsicherheit steht "bitte prüfen".',
    noPages: 'Es wurden keine Seiten inhaltlich bewertet.',
    roadmapUnits: { WEEK: '7', MONTH: '30', QUARTER: '90' },
    roadmapDaysUnit: 'Tage',
    roadmapResult: 'Wirkung',
    methodCards: { crawl: 'Crawl', judged: 'Bewertung', summary: 'Zusammenfassung', limits: 'Grenzen' },
    methodCrawl: (pages, date) => `${pages} Seiten am ${date} gelesen. Alles Zählbare zählt der Code: Statuscodes, Titel, Überschriften, Links, HTTPS, Ladezeit, strukturierte Daten.`,
    methodJudged:
      'Seitentyp, Suchabsicht, Hilfreichkeit, Konkretheit und Vertrauen sowie die Relevanz der Keywords beurteilt ein KI-Modell. Die Sicherheit ist seine Selbsteinschätzung. Bei Unsicherheit steht "bitte prüfen".',
    methodSummary: (model, isFullyVerified) =>
      `${model} schreibt sie aus den Messwerten. Jede Zahl im Text wird gegen den Audit geprüft. ${isFullyVerified ? 'Alle Zahlen sind belegt.' : 'Nicht belegte Zahlen sind markiert.'}`,
    methodNoSummary: 'Die Zusammenfassung stammt aus festen Textbausteinen, nicht von einem Modell.',
    ctaEyebrow: 'Nächster Schritt',
    ctaLine1: "Let's talk",
    ctaLine2: 'growth.',
    ctaText: (tasks) =>
      `Wir gehen die ${tasks} Maßnahmen gemeinsam durch und setzen die wichtigsten um.`,
    ctaButton: 'Gespräch buchen',
    headerButton: 'Gespräch buchen',
    footerLegal: 'Erstellt auf Basis öffentlich zugänglicher Daten. Keine Rechtsberatung.',
    footerStudio: 'Independent Digital Growth Studio',
  },
  EN: {
    heroEyebrow: (domain, date) => `Audit · ${domain} · ${date}`,
    heroHeadline: 'SEO audit',
    metaPages: 'Checked',
    metaDate: 'As of',
    metaEngines: 'AI engines',
    gaugeCaption: 'OVERALL SCORE / 100',
    gradeWord: 'Grade',
    rulesOnlyAverage: (rulesOnly) => `Measured rules only: ${rulesOnly}`,
    marquee: ['Technical SEO', 'AI Visibility', 'Content', 'Entity & Schema', 'Core Web Vitals', 'Citations'],
    openReport: 'Save as PDF',
    sections: {
      summary: { eyebrow: 'The essentials', plain: 'The essentials', accent: 'in brief.' },
      scorecard: { eyebrow: 'Scorecard', plain: 'The areas.', accent: 'One picture.' },
      ai: { eyebrow: 'AI visibility', plain: 'When customers', accent: 'ask AI.' },
      findings: { eyebrow: 'The biggest levers', plain: 'Where the', accent: 'leverage is.' },
      pages: { eyebrow: 'Pages in detail', plain: 'Every page', accent: 'judged.' },
      market: { eyebrow: 'Visibility and market', plain: 'Visible', accent: 'in the market.' },
      opportunities: { eyebrow: 'Opportunities', plain: 'Where a page', accent: 'is missing.' },
      strengths: { eyebrow: 'What already works', plain: 'A good', accent: 'base.' },
      roadmap: { eyebrow: 'The path', plain: 'The path', accent: 'in three steps.' },
      method: { eyebrow: 'Method and transparency', plain: 'How we checked', accent: '' },
    },
    strengthTitles: {
      STRONG_AREAS: 'Strong areas',
      TOP_RANKINGS: 'Top rankings',
      HELPFUL_PAGES: 'Helpful pages',
      AI_READINESS: 'AI readiness',
      AI_PRESENCE: 'Named in AI answers',
    },
    scorecardLead:
      'Every area is rated on its own and enters the overall score with its weight.',
    tasksInArea: (count) => `${count} open ${count === 1 ? 'action' : 'actions'}`,
    noTasksInArea: 'No action needed',
    impactEyebrow: 'Content judgement',
    impactTitle: (rulesOnly, score) =>
      `By the measured rules alone the score would be ${rulesOnly}. With the judgement of content and keywords it is ${score}.`,
    impactHint: 'A purely technical audit does not see this difference.',
    summaryBlockers: 'What holds the site back',
    summaryStrengths: 'What works',
    evidence: 'Evidence',
    recommendation: 'Fix',
    affected: 'Affected',
    effortLabel: 'Effort',
    sourceLabel: 'Source',
    horizonLabel: 'Horizon',
    moreMeasures: 'More actions',
    findingsLead: (shown, total) =>
      total > shown
        ? `The ${shown} most important of ${total} actions, each with evidence and fix. The rest follows below.`
        : `All ${total} actions, each with evidence and fix.`,
    aiReadinessChips: 'AI readiness',
    aiPresence: 'Share of answers that name the website',
    aiTestedOn: (date) => `Tested on ${date}. Results can vary between sessions.`,
    pagesLead:
      'Every page was judged on its own. 1 is weak, 5 is strong. When the model is unsure it says "please check".',
    noPages: 'No pages were judged for content.',
    roadmapUnits: { WEEK: '7', MONTH: '30', QUARTER: '90' },
    roadmapDaysUnit: 'days',
    roadmapResult: 'Effect',
    methodCards: { crawl: 'Crawl', judged: 'Judgement', summary: 'Summary', limits: 'Limits' },
    methodCrawl: (pages, date) => `${pages} pages read on ${date}. The code counts everything countable: status codes, titles, headings, links, HTTPS, load time, structured data.`,
    methodJudged:
      'Page type, search intent, helpfulness, specificity and trust as well as keyword relevance are judged by an AI model. Its confidence is a self-assessment. When it is unsure the report says "please check".',
    methodSummary: (model, isFullyVerified) =>
      `${model} writes it from the measurements. Every number in the text is checked against the audit. ${isFullyVerified ? 'Every number is backed up.' : 'Numbers that are not backed up are marked.'}`,
    methodNoSummary: 'The summary comes from fixed text blocks, not from a model.',
    ctaEyebrow: 'Next step',
    ctaLine1: "Let's talk",
    ctaLine2: 'growth.',
    ctaText: (tasks) =>
      `We go through the ${tasks} actions together and implement the most important ones.`,
    ctaButton: 'Book a call',
    headerButton: 'Book a call',
    footerLegal: 'Based on publicly available data. Not legal advice.',
    footerStudio: 'Independent Digital Growth Studio',
  },
};
