import { type AuditLanguage } from 'src/types/audit-language';
import { type ReportDesignLabels } from 'src/types/report-design-labels';

export const REPORT_DESIGN_LABELS: Record<AuditLanguage, ReportDesignLabels> = {
  DE: {
    heroEyebrow: (domain, date) => `Audit · ${domain} · ${date}`,
    heroHeadline: 'SEO-Audit',
    metaPages: 'Seiten geprüft',
    metaDate: 'Stand',
    metaEngines: 'KI-Assistenten getestet',
    gaugeCaption: 'GESAMTSCORE / 100',
    gradeWord: 'Note',
    technicalOnlyScore: (technicalScore) => `Nur Technik: ${technicalScore}`,
    marquee: ['Technical SEO', 'AI Visibility', 'Content', 'Entity & Schema', 'Core Web Vitals', 'Citations'],
    openReport: 'Als PDF speichern',
    sections: {
      summary: { eyebrow: 'Das Wichtigste', plain: 'Das Wichtigste', accent: 'in Kürze.' },
      scorecard: { eyebrow: 'Scorecard', plain: 'Die Bereiche.', accent: 'Ein Bild.' },
      strengths: { eyebrow: 'Was bereits funktioniert', plain: 'Eine gute', accent: 'Basis.' },
      ai: { eyebrow: 'KI-Sichtbarkeit', plain: 'Wenn Kunden', accent: 'die KI fragen.' },
      aiReadiness: { eyebrow: 'KI-Sichtbarkeit', plain: 'Bereit für', accent: 'die KI-Suche?' },
      findings: { eyebrow: 'Die größten Hebel', plain: 'Hier verschenkt', accent: 'die Website Anfragen.' },
      pages: { eyebrow: 'Seiten im Detail', plain: 'Jede Seite', accent: 'einzeln bewertet.' },
      market: { eyebrow: 'Sichtbarkeit und Markt', plain: 'Sichtbar', accent: 'im Markt.' },
      opportunities: { eyebrow: 'Chancen', plain: 'Hier fehlt', accent: 'eine Seite.' },
      roadmap: { eyebrow: 'Der Weg', plain: 'Der Weg', accent: 'in drei Schritten.' },
      method: { eyebrow: 'Methodik und Transparenz', plain: 'So haben wir geprüft', accent: '' },
    },
    strengthTitles: {
      STRONG_AREAS: 'Starke Bereiche',
      TOP_RANKINGS: 'Top-Rankings',
      HELPFUL_PAGES: 'Hilfreiche Seiten',
      AI_READINESS: 'KI-Bereitschaft',
      AI_PRESENCE: 'In KI-Antworten genannt',
    },
    scorecardLead:
      'Jeder Bereich wird einzeln bewertet und mit seinem Gewicht in den Gesamtscore übernommen.',
    tasksInArea: (count) => `${count} ${count === 1 ? 'Ansatzpunkt' : 'Ansatzpunkte'}`,
    impactEyebrow: 'Technik ist nicht alles',
    impactTitle: (technicalScore, score) =>
      `Ein rein technischer Check käme auf ${technicalScore} Punkte. Mit Inhalt und Auffindbarkeit sind es ${score}.`,
    impactHint: 'Der Unterschied entsteht dort, wo Besucher zu Kunden werden. Ein technischer Check sieht ihn nicht.',
    whyItMatters: 'Warum das zählt',
    areaImpact: {
      CRAWLABILITY: 'Google kann Inhalte nicht zuverlässig lesen und zeigt sie dann nicht oder nur unvollständig an.',
      ON_PAGE: 'Unklare oder doppelte Seitenangaben kosten Klicks in den Suchergebnissen und lassen Seiten gegeneinander antreten.',
      CONTENT_QUALITY: 'Seiten, die nicht überzeugen, verlieren Besucher, bevor aus ihnen Anfragen werden.',
      VISIBILITY: 'Die Website taucht für Suchen, die Kunden wirklich stellen, zu weit hinten oder gar nicht auf.',
      AI_VISIBILITY: 'KI-Assistenten empfehlen immer häufiger Anbieter. Hier entscheidet sich, ob dein Unternehmen genannt wird.',
      LINKS: 'Ins Leere laufende Wege frustrieren Besucher und kosten Vertrauen bei Google.',
      STRUCTURED_DATA: 'Ohne klare Auszeichnung verstehen Suchmaschinen und KI nicht sicher, wer du bist und was du anbietest.',
      PERFORMANCE: 'Langsame Seiten verlieren Besucher, vor allem auf dem Handy.',
      SECURITY: 'Browser warnen oder blockieren Inhalte. Das untergräbt Vertrauen genau dort, wo Kunden entscheiden.',
    },
    affected: 'Betroffen',
    affectedMore: (count) => `und ${count} weitere`,
    findingsLead: (shown, total) =>
      total > shown
        ? `Die ${shown} wichtigsten von ${total} Punkten. Jeder davon kostet Besucher, Vertrauen oder Anfragen.`
        : `Alle ${total} Punkte. Jeder davon kostet Besucher, Vertrauen oder Anfragen.`,
    otherFindingsHeading: 'Weitere Punkte',
    otherFindingsLead: (count, areaCount) =>
      `Dazu kommen ${count} weitere Punkte in ${areaCount} ${areaCount === 1 ? 'Bereich' : 'Bereichen'}. Sie hängen zusammen, und die Reihenfolge entscheidet, was sich lohnt.`,
    aiReadinessChips: 'KI-Bereitschaft',
    aiPresence: 'Anteil der Antworten, die die Website nennen',
    aiTestedOn: (date) => `Getestet am ${date}. Ergebnisse können je Sitzung variieren.`,
    pagesLead:
      'Jede Seite wurde einzeln bewertet: wie hilfreich, konkret und vertrauenswürdig sie für Besucher ist. 1 ist schwach, 5 ist stark.',
    roadmapLead: 'In welcher Reihenfolge die Arbeit am meisten bringt. Jede Stufe baut auf der vorherigen auf.',
    roadmapUnits: { WEEK: '7', MONTH: '30', QUARTER: '90' },
    roadmapDaysUnit: 'Tage',
    roadmapMeasures: (count) => `${count} ${count === 1 ? 'Maßnahme' : 'Maßnahmen'}`,
    roadmapNothing: 'Hier steht nichts Dringendes an.',
    roadmapResult: 'Wirkung',
    methodCards: { crawl: 'Crawl', judged: 'Bewertung', summary: 'Zusammenfassung', limits: 'Einordnung' },
    methodCrawl: (pages, date) =>
      `${pages} Seiten am ${date} gelesen. Alles Zählbare wurde gemessen: Statuscodes, Titel, Überschriften, Links, HTTPS, Ladezeit, strukturierte Daten.`,
    methodJudged:
      'Seitentyp, Suchabsicht, Hilfreichkeit, Konkretheit und Vertrauen wurden für jede Seite einzeln beurteilt. Unsichere Urteile fließen nicht in die Maßnahmen ein.',
    methodSummary: 'Jede Zahl in der Zusammenfassung wurde gegen die Messwerte geprüft.',
    methodLimits:
      'Der Audit ist eine Momentaufnahme. Rankings und Antworten von KI-Assistenten schwanken, der Score ist ein Orientierungswert und keine Garantie. Er zeigt, wo es hakt, nicht in welcher Reihenfolge sich die Arbeit lohnt.',
    ctaEyebrow: 'Nächster Schritt',
    ctaLine1: "Let's talk",
    ctaLine2: 'growth.',
    ctaText:
      'In 30 Minuten gehen wir den Audit mit dir durch und legen fest, was zuerst Anfragen bringt. Danach setzen wir es für dich um, wenn du möchtest.',
    ctaButton: 'Gespräch buchen',
    headerButton: 'Gespräch buchen',
    footerLegal: 'Erstellt auf Basis öffentlich zugänglicher Daten. Keine Rechtsberatung.',
    footerStudio: 'Independent Digital Growth Studio',
  },
  EN: {
    heroEyebrow: (domain, date) => `Audit · ${domain} · ${date}`,
    heroHeadline: 'SEO audit',
    metaPages: 'Pages checked',
    metaDate: 'As of',
    metaEngines: 'AI assistants tested',
    gaugeCaption: 'OVERALL SCORE / 100',
    gradeWord: 'Grade',
    technicalOnlyScore: (technicalScore) => `Technical only: ${technicalScore}`,
    marquee: ['Technical SEO', 'AI Visibility', 'Content', 'Entity & Schema', 'Core Web Vitals', 'Citations'],
    openReport: 'Save as PDF',
    sections: {
      summary: { eyebrow: 'The essentials', plain: 'The essentials', accent: 'in brief.' },
      scorecard: { eyebrow: 'Scorecard', plain: 'The areas.', accent: 'One picture.' },
      strengths: { eyebrow: 'What already works', plain: 'A good', accent: 'base.' },
      ai: { eyebrow: 'AI visibility', plain: 'When customers', accent: 'ask AI.' },
      aiReadiness: { eyebrow: 'AI visibility', plain: 'Ready for', accent: 'AI search?' },
      findings: { eyebrow: 'The biggest levers', plain: 'Where the website', accent: 'loses inquiries.' },
      pages: { eyebrow: 'Pages in detail', plain: 'Every page', accent: 'judged.' },
      market: { eyebrow: 'Visibility and market', plain: 'Visible', accent: 'in the market.' },
      opportunities: { eyebrow: 'Opportunities', plain: 'Where a page', accent: 'is missing.' },
      roadmap: { eyebrow: 'The path', plain: 'The path', accent: 'in three steps.' },
      method: { eyebrow: 'Method and transparency', plain: 'How we checked', accent: '' },
    },
    strengthTitles: {
      STRONG_AREAS: 'Strong areas',
      TOP_RANKINGS: 'Top rankings',
      HELPFUL_PAGES: 'Helpful pages',
      AI_READINESS: 'AI readiness',
      AI_PRESENCE: 'Named in AI answers',
    },
    scorecardLead: 'Every area is rated on its own and enters the overall score with its weight.',
    tasksInArea: (count) => `${count} ${count === 1 ? 'starting point' : 'starting points'}`,
    impactEyebrow: 'Technology is not everything',
    impactTitle: (technicalScore, score) =>
      `A purely technical check would give ${technicalScore} points. With content and findability it is ${score}.`,
    impactHint: 'The difference arises where visitors become customers. A technical check does not see it.',
    whyItMatters: 'Why it matters',
    areaImpact: {
      CRAWLABILITY: 'Google cannot reliably read the content and then shows it incompletely or not at all.',
      ON_PAGE: 'Unclear or duplicate page details cost clicks in search results and make pages compete with each other.',
      CONTENT_QUALITY: 'Pages that do not convince lose visitors before they turn into inquiries.',
      VISIBILITY: 'The website shows up too far back, or not at all, for searches customers really make.',
      AI_VISIBILITY: 'AI assistants recommend providers more and more often. This decides whether your business is named.',
      LINKS: 'Paths that lead nowhere frustrate visitors and cost trust with Google.',
      STRUCTURED_DATA: 'Without clear markup, search engines and AI cannot be sure who you are and what you offer.',
      PERFORMANCE: 'Slow pages lose visitors, especially on mobile.',
      SECURITY: 'Browsers warn or block content. That undermines trust exactly where customers decide.',
    },
    affected: 'Affected',
    affectedMore: (count) => `and ${count} more`,
    findingsLead: (shown, total) =>
      total > shown
        ? `The ${shown} most important of ${total} points. Each one costs visitors, trust or inquiries.`
        : `All ${total} points. Each one costs visitors, trust or inquiries.`,
    otherFindingsHeading: 'More points',
    otherFindingsLead: (count, areaCount) =>
      `There are ${count} more points in ${areaCount} ${areaCount === 1 ? 'area' : 'areas'}. They are connected, and the order decides what pays off.`,
    aiReadinessChips: 'AI readiness',
    aiPresence: 'Share of answers that name the website',
    aiTestedOn: (date) => `Tested on ${date}. Results can vary between sessions.`,
    pagesLead:
      'Every page was judged on its own: how helpful, specific and trustworthy it is for visitors. 1 is weak, 5 is strong.',
    roadmapLead: 'The order in which the work pays off most. Each step builds on the previous one.',
    roadmapUnits: { WEEK: '7', MONTH: '30', QUARTER: '90' },
    roadmapDaysUnit: 'days',
    roadmapMeasures: (count) => `${count} ${count === 1 ? 'action' : 'actions'}`,
    roadmapNothing: 'Nothing urgent is due here.',
    roadmapResult: 'Effect',
    methodCards: { crawl: 'Crawl', judged: 'Judgement', summary: 'Summary', limits: 'Context' },
    methodCrawl: (pages, date) =>
      `${pages} pages read on ${date}. Everything countable was measured: status codes, titles, headings, links, HTTPS, load time, structured data.`,
    methodJudged:
      'Page type, search intent, helpfulness, specificity and trust were judged for every page on its own. Uncertain judgements do not feed into the actions.',
    methodSummary: 'Every number in the summary was checked against the measurements.',
    methodLimits:
      'The audit is a snapshot. Rankings and answers of AI assistants vary, and the score is a guide, not a guarantee. It shows where things hold up, not in which order the work pays off.',
    ctaEyebrow: 'Next step',
    ctaLine1: "Let's talk",
    ctaLine2: 'growth.',
    ctaText:
      'In 30 minutes we go through the audit with you and decide what brings inquiries first. Afterwards we implement it for you, if you like.',
    ctaButton: 'Book a call',
    headerButton: 'Book a call',
    footerLegal: 'Based on publicly available data. Not legal advice.',
    footerStudio: 'Independent Digital Growth Studio',
  },
};
