import { type AuditLanguage } from 'src/types/audit-language';
import { type ReportLabels } from 'src/types/report-labels';

export const REPORT_LABELS: Record<AuditLanguage, ReportLabels> = {
  DE: {
    title: 'SEO-Audit',
    generatedOn: 'Erstellt am',
    score: 'Gesamtscore',
    grade: 'Note',
    pagesChecked: 'Seiten geprüft',
    areasHeading: 'Bereiche',
    areaColumn: 'Bereich',
    scoreColumn: 'Score',
    summaryHeading: 'Zusammenfassung',
    strongestArea: 'Stärkster Bereich',
    weakestArea: 'Schwächster Bereich',
    taskCount: 'Maßnahmen insgesamt',
    criticalCount: 'davon kritisch',
    noTasks: 'Es wurden keine Maßnahmen gefunden.',
    tasksHeading: 'Maßnahmenliste',
    horizonWeek: 'Diese Woche',
    horizonMonth: 'Diesen Monat',
    horizonQuarter: 'Dieses Quartal',
    priorityColumn: 'Priorität',
    effortColumn: 'Aufwand',
    sourceColumn: 'Quelle',
    taskColumn: 'Maßnahme',
    affectedUrls: 'Betroffene URLs',
    moreUrls: 'weitere',
    reviewHeading: 'Bitte manuell prüfen',
    reviewIntro:
      'Bei diesen Seiten war die automatische Bewertung unsicher. Sie fließen nicht in die Maßnahmen ein.',
    methodologyHeading: 'Methodik',
    methodology:
      'Gemessen (Quelle "Regel"): Statuscodes, Titles, Descriptions, Überschriften, Links, HTTPS, Antwortzeit und strukturierte Daten werden vom Code gezählt und nicht geschätzt. Beurteilt (Quelle "Klassifikator"): Seitentyp, Suchintention, Hilfreichkeit, Konkretheit und Vertrauen bewertet ein Sprachmodell. Die Konfidenz ist eine Selbsteinschätzung des Modells und keine berechnete Wahrscheinlichkeit. Rankings, Suchvolumen, Backlinks und Wettbewerber stammen von DataForSEO. Der Sichtbarkeits-Score gewichtet die Platzierungen relevanter Keywords nach Suchvolumen.',
    contentNotAssessed:
      'Die Inhaltsqualität wurde nicht bewertet, weil kein Klassifikator konfiguriert war. Der Gesamtscore beruht nur auf gemessenen Regeln.',
    marketDataNotConfigured:
      'Rankings, Keywords und Backlinks fehlen, weil DataForSEO nicht eingerichtet ist. Du kannst es im Setup-Tab ergänzen.',
    marketHeading: 'Sichtbarkeit und Markt',
    marketNotes: 'Nicht verfügbar',
    keywordsTotal: 'Keywords mit Google-Ranking',
    trafficEstimate: 'Geschätzte Besucher pro Monat',
    positionsHeading: 'Verteilung der Platzierungen',
    opportunitiesHeading: 'Keyword-Chancen',
    keywordColumn: 'Keyword',
    positionColumn: 'Platz',
    volumeColumn: 'Suchen pro Monat',
    pageColumn: 'Seite',
    notRelevantHeading: 'Aussortierte Rankings',
    notRelevantIntro:
      'Für diese Keywords rankt die Website, sie passen aber nicht zum Unternehmen und bringen keine Kunden.',
    backlinksHeading: 'Backlinks',
    backlinksTotal: 'Backlinks',
    referringDomains: 'Verweisende Domains',
    brokenBacklinkPages: 'Verlinkte Seiten, die nicht mehr existieren',
    competitorsHeading: 'Wettbewerber',
    domainColumn: 'Domain',
    commonKeywordsColumn: 'Gemeinsame Keywords',
    trafficColumn: 'Geschätzte Besucher',
    keywordCategories: { QUICK_WIN: 'Platz 4 bis 10', NEAR_PAGE_ONE: 'Platz 11 bis 30' },
    areas: {
      CRAWLABILITY: 'Crawling',
      ON_PAGE: 'On-Page',
      CONTENT_QUALITY: 'Inhaltsqualität',
      LINKS: 'Links',
      STRUCTURED_DATA: 'Strukturierte Daten',
      PERFORMANCE: 'Ladezeit',
      SECURITY: 'Sicherheit',
      VISIBILITY: 'Sichtbarkeit',
    },
    priorities: {
      CRITICAL: 'Kritisch',
      HIGH: 'Hoch',
      MEDIUM: 'Mittel',
      LOW: 'Niedrig',
    },
    efforts: { LOW: 'Gering', MEDIUM: 'Mittel', HIGH: 'Hoch' },
    sources: { RULE: 'Regel', CLASSIFIER: 'Klassifikator' },
  },
  EN: {
    title: 'SEO audit',
    generatedOn: 'Generated on',
    score: 'Overall score',
    grade: 'Grade',
    pagesChecked: 'pages checked',
    areasHeading: 'Areas',
    areaColumn: 'Area',
    scoreColumn: 'Score',
    summaryHeading: 'Summary',
    strongestArea: 'Strongest area',
    weakestArea: 'Weakest area',
    taskCount: 'Total actions',
    criticalCount: 'of which critical',
    noTasks: 'No actions were found.',
    tasksHeading: 'Action list',
    horizonWeek: 'This week',
    horizonMonth: 'This month',
    horizonQuarter: 'This quarter',
    priorityColumn: 'Priority',
    effortColumn: 'Effort',
    sourceColumn: 'Source',
    taskColumn: 'Action',
    affectedUrls: 'Affected URLs',
    moreUrls: 'more',
    reviewHeading: 'Please review manually',
    reviewIntro:
      'The automatic assessment was unsure about these pages. They do not feed into the actions.',
    methodologyHeading: 'Methodology',
    methodology:
      'Measured (source "Rule"): status codes, titles, descriptions, headings, links, HTTPS, response time and structured data are counted by code, never estimated. Judged (source "Classifier"): page type, search intent, helpfulness, specificity and trust are rated by a language model. Confidence is the model self-assessment, not a computed probability. Rankings, search volume, backlinks and competitors come from DataForSEO. The visibility score weights the positions of relevant keywords by search volume.',
    contentNotAssessed:
      'Content quality was not assessed because no classifier was configured. The overall score only reflects measured rules.',
    marketDataNotConfigured:
      'Rankings, keywords and backlinks are missing because DataForSEO is not set up. You can add it in the Setup tab.',
    marketHeading: 'Visibility and market',
    marketNotes: 'Not available',
    keywordsTotal: 'Keywords ranking on Google',
    trafficEstimate: 'Estimated monthly visitors',
    positionsHeading: 'Position distribution',
    opportunitiesHeading: 'Keyword opportunities',
    keywordColumn: 'Keyword',
    positionColumn: 'Position',
    volumeColumn: 'Searches per month',
    pageColumn: 'Page',
    notRelevantHeading: 'Filtered out rankings',
    notRelevantIntro:
      'The website ranks for these keywords, but they do not fit the business and bring no customers.',
    backlinksHeading: 'Backlinks',
    backlinksTotal: 'Backlinks',
    referringDomains: 'Referring domains',
    brokenBacklinkPages: 'Linked pages that no longer exist',
    competitorsHeading: 'Competitors',
    domainColumn: 'Domain',
    commonKeywordsColumn: 'Shared keywords',
    trafficColumn: 'Estimated visitors',
    keywordCategories: { QUICK_WIN: 'Positions 4 to 10', NEAR_PAGE_ONE: 'Positions 11 to 30' },
    areas: {
      CRAWLABILITY: 'Crawlability',
      ON_PAGE: 'On-page',
      CONTENT_QUALITY: 'Content quality',
      LINKS: 'Links',
      STRUCTURED_DATA: 'Structured data',
      PERFORMANCE: 'Performance',
      SECURITY: 'Security',
      VISIBILITY: 'Visibility',
    },
    priorities: {
      CRITICAL: 'Critical',
      HIGH: 'High',
      MEDIUM: 'Medium',
      LOW: 'Low',
    },
    efforts: { LOW: 'Low', MEDIUM: 'Medium', HIGH: 'High' },
    sources: { RULE: 'Rule', CLASSIFIER: 'Classifier' },
  },
};
