import { type AuditLanguage } from 'src/types/audit-language';
import { type ReportLabels } from 'src/types/report-labels';

export const REPORT_LABELS: Record<AuditLanguage, ReportLabels> = {
  DE: {
    title: 'SEO-Audit',
    generatedOn: 'Erstellt am',
    score: 'Gesamtscore',
    grade: 'Note',
    pagesChecked: 'Seiten geprüft',
    areasHeading: 'Bereiche',
    areaColumn: 'Bereich',
    scoreColumn: 'Score',
    summaryHeading: 'Zusammenfassung',
    strongestArea: 'Stärkster Bereich',
    weakestArea: 'Schwächster Bereich',
    taskCount: 'Maßnahmen insgesamt',
    criticalCount: 'davon kritisch',
    noTasks: 'Es wurden keine Maßnahmen gefunden.',
    tasksHeading: 'Maßnahmenliste',
    horizonWeek: 'Diese Woche',
    horizonMonth: 'Diesen Monat',
    horizonQuarter: 'Dieses Quartal',
    priorityColumn: 'Priorität',
    effortColumn: 'Aufwand',
    sourceColumn: 'Quelle',
    taskColumn: 'Maßnahme',
    affectedUrls: 'Betroffene URLs',
    moreUrls: 'weitere',
    reviewHeading: 'Bitte manuell prüfen',
    reviewIntro:
      'Bei diesen Seiten war die automatische Bewertung unsicher. Sie fließen nicht in die Maßnahmen ein.',
    methodologyHeading: 'Methodik',
    methodology:
      'Gemessen (Quelle "Regel"): Statuscodes, Titles, Descriptions, Überschriften, Links, HTTPS, Antwortzeit und strukturierte Daten werden vom Code gezählt und nicht geschätzt. Beurteilt (Quelle "Klassifikator"): Seitentyp, Suchintention, Hilfreichkeit, Konkretheit und Vertrauen bewertet ein Sprachmodell. Die Konfidenz ist eine Selbsteinschätzung des Modells und keine berechnete Wahrscheinlichkeit.',
    contentNotAssessed:
      'Die Inhaltsqualität wurde nicht bewertet, weil kein Klassifikator konfiguriert war. Der Gesamtscore beruht nur auf gemessenen Regeln.',
    areas: {
      CRAWLABILITY: 'Crawling',
      ON_PAGE: 'On-Page',
      CONTENT_QUALITY: 'Inhaltsqualität',
      LINKS: 'Links',
      STRUCTURED_DATA: 'Strukturierte Daten',
      PERFORMANCE: 'Ladezeit',
      SECURITY: 'Sicherheit',
    },
    priorities: {
      CRITICAL: 'Kritisch',
      HIGH: 'Hoch',
      MEDIUM: 'Mittel',
      LOW: 'Niedrig',
    },
    efforts: { LOW: 'Gering', MEDIUM: 'Mittel', HIGH: 'Hoch' },
    sources: { RULE: 'Regel', CLASSIFIER: 'Klassifikator' },
  },
  EN: {
    title: 'SEO audit',
    generatedOn: 'Generated on',
    score: 'Overall score',
    grade: 'Grade',
    pagesChecked: 'pages checked',
    areasHeading: 'Areas',
    areaColumn: 'Area',
    scoreColumn: 'Score',
    summaryHeading: 'Summary',
    strongestArea: 'Strongest area',
    weakestArea: 'Weakest area',
    taskCount: 'Total actions',
    criticalCount: 'of which critical',
    noTasks: 'No actions were found.',
    tasksHeading: 'Action list',
    horizonWeek: 'This week',
    horizonMonth: 'This month',
    horizonQuarter: 'This quarter',
    priorityColumn: 'Priority',
    effortColumn: 'Effort',
    sourceColumn: 'Source',
    taskColumn: 'Action',
    affectedUrls: 'Affected URLs',
    moreUrls: 'more',
    reviewHeading: 'Please review manually',
    reviewIntro:
      'The automatic assessment was unsure about these pages. They do not feed into the actions.',
    methodologyHeading: 'Methodology',
    methodology:
      'Measured (source "Rule"): status codes, titles, descriptions, headings, links, HTTPS, response time and structured data are counted by code, never estimated. Judged (source "Classifier"): page type, search intent, helpfulness, specificity and trust are rated by a language model. Confidence is the model self-assessment, not a computed probability.',
    contentNotAssessed:
      'Content quality was not assessed because no classifier was configured. The overall score only reflects measured rules.',
    areas: {
      CRAWLABILITY: 'Crawlability',
      ON_PAGE: 'On-page',
      CONTENT_QUALITY: 'Content quality',
      LINKS: 'Links',
      STRUCTURED_DATA: 'Structured data',
      PERFORMANCE: 'Performance',
      SECURITY: 'Security',
    },
    priorities: {
      CRITICAL: 'Critical',
      HIGH: 'High',
      MEDIUM: 'Medium',
      LOW: 'Low',
    },
    efforts: { LOW: 'Low', MEDIUM: 'Medium', HIGH: 'High' },
    sources: { RULE: 'Rule', CLASSIFIER: 'Classifier' },
  },
};
