export const SEO_AUDIT_STATUS = {
  QUEUED: 'QUEUED',
  RUNNING: 'RUNNING',
  DONE: 'DONE',
  FAILED: 'FAILED',
} as const;

export const SEO_AUDIT_TASK_STATUS = {
  OPEN: 'OPEN',
  IN_PROGRESS: 'IN_PROGRESS',
  DONE: 'DONE',
  WONT_FIX: 'WONT_FIX',
} as const;

export const SEO_AUDIT_LANGUAGE = {
  DE: 'DE',
  EN: 'EN',
} as const;

export const SEO_AREA = {
  CRAWLABILITY: 'CRAWLABILITY',
  ON_PAGE: 'ON_PAGE',
  CONTENT_QUALITY: 'CONTENT_QUALITY',
  LINKS: 'LINKS',
  STRUCTURED_DATA: 'STRUCTURED_DATA',
  PERFORMANCE: 'PERFORMANCE',
  SECURITY: 'SECURITY',
  VISIBILITY: 'VISIBILITY',
} as const;

export const SEO_PRIORITY = {
  CRITICAL: 'CRITICAL',
  HIGH: 'HIGH',
  MEDIUM: 'MEDIUM',
  LOW: 'LOW',
} as const;

export const SEO_EFFORT = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
} as const;

export const SEO_TASK_SOURCE = {
  RULE: 'RULE',
  CLASSIFIER: 'CLASSIFIER',
} as const;

export const PAGE_TYPE = {
  HOME: 'HOME',
  SERVICE: 'SERVICE',
  PRODUCT: 'PRODUCT',
  CATEGORY: 'CATEGORY',
  ARTICLE: 'ARTICLE',
  ABOUT: 'ABOUT',
  CONTACT: 'CONTACT',
  LEGAL: 'LEGAL',
  LANDING: 'LANDING',
  OTHER: 'OTHER',
} as const;

export const SEARCH_INTENT = {
  INFORMATIONAL: 'INFORMATIONAL',
  COMMERCIAL: 'COMMERCIAL',
  TRANSACTIONAL: 'TRANSACTIONAL',
  NAVIGATIONAL: 'NAVIGATIONAL',
  NONE: 'NONE',
} as const;

export const BUSINESS_MODEL = {
  LOCAL_SERVICE: 'LOCAL_SERVICE',
  ECOMMERCE: 'ECOMMERCE',
  B2B_SERVICE: 'B2B_SERVICE',
  CONTENT_PUBLISHER: 'CONTENT_PUBLISHER',
  SAAS: 'SAAS',
  OTHER: 'OTHER',
} as const;

export const STUCK_AUDIT_TIMEOUT_MINUTES = 20;

export const KEYWORD_CATEGORY = {
  TOP_3: 'TOP_3',
  QUICK_WIN: 'QUICK_WIN',
  NEAR_PAGE_ONE: 'NEAR_PAGE_ONE',
  LOW_RANKING: 'LOW_RANKING',
  NOT_RELEVANT: 'NOT_RELEVANT',
  NEEDS_REVIEW: 'NEEDS_REVIEW',
} as const;
