export const AGENT_TASK_STATUS = {
  QUEUED: 'QUEUED',
  RUNNING: 'RUNNING',
  WAITING_APPROVAL: 'WAITING_APPROVAL',
  DONE: 'DONE',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED',
} as const;

export const APPROVAL_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
} as const;

export const AGENT_ROLE = {
  LEAD_SALES: 'LEAD_SALES',
  ACCOUNT_MANAGER: 'ACCOUNT_MANAGER',
  STRATEGIST: 'STRATEGIST',
  CONTENT_SEO: 'CONTENT_SEO',
  PAID_MEDIA: 'PAID_MEDIA',
  WEB_DEV: 'WEB_DEV',
  REPORTING: 'REPORTING',
  FINANCE: 'FINANCE',
  QA_SUPERVISOR: 'QA_SUPERVISOR',
} as const;

export const RUNNING_TASK_TIMEOUT_MINUTES = 120;
